
server:
  port: 80

spring:
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true

--- #dev

spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false